protected/models/Comment.php
<?php

/**
 * This is the model class for table "{{comment}}".
 *
 * The followings are the available columns in table '{{comment}}':
 * @property integer $id
 * @property string $content
 * @property integer $status
 * @property integer $create_time
 * @property string $author
 * @property string $email
 * @property string $url
 * @property integer $post_id
 *
 * The followings are the available model relations:
 * @property Post $post
 */
class Comment extends CActiveRecord
{
	const STATUS_PENDING = 1;
    const STATUS_APPROVED = 2;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{comment}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		return array(
	        array('content, author, email', 'required', 'message'=>'{attribute} не может быть пустым.'),
            array('content', 'ext.decoda.DecodaValidator', 'useParsed'=>false),
	        array('author, email, url', 'length', 'max'=>128),
	        array('email','email', 'message'=>'Проверьте правильность ввода эл.почты.'),
	        array('url','url', 'message'=>'Адрес сайта введён некорректно.'),
            ['status', 'in', 'range' => [1, 2] ],
            ['status', 'safe', 'on'=>'search'],
	    );
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'post' => array(self::BELONGS_TO, 'Post', 'post_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
            'id'=>'ID',
	        'content' => 'Комментарий',
	        'status' => 'Статус',
	        'create_time' => 'Дата',
	        'author' => 'Имя',
	        'email' => 'Эл. почта',
	        'url' => 'Сайт',
	        'post_id' => 'Пост',
	    );
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		$criteria=new CDbCriteria;

		$criteria->compare('status',$this->status);
		$criteria->compare('author',$this->author,true);
		$criteria->compare('email',$this->email,true);
        $criteria->with='post';

		return new CActiveDataProvider($this, array(
            'pagination'=>
                ['pageSize'=>20],
			'criteria'=>$criteria,
            'sort' => array(
                'defaultOrder' => 't.status, t.create_time DESC',
            ),
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Comment the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	protected function beforeSave()
	{
	    if(parent::beforeSave())
	    {
	        if($this->isNewRecord) {
	            $this->create_time=time();
                $this->content=Yii::app()->decoda->parse($this->content);
            }
            else {
                $this->create_time = strtotime($this->create_time);
            }
	        return true;
	    }
	    else
	        return false;
	}

	public function approve()
	{
	    $this->status=Comment::STATUS_APPROVED;
	    $this->update(array('status'));
	}
	
	protected function afterFind() {
 		parent::afterFind();
		$this->create_time = date('d.m.Y H:i', $this->create_time);
	}

    public function getPendingCommentCount() {
        return $this->count('status=:status',['status'=>Comment::STATUS_PENDING]);;
    }
}

protected/controllers/CommentController.php
<?php

class CommentController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
            'postOnly + approve',
		);
	}

    public function actions()
    {
        return array(
            'imageUpload'=>array(
                'class'=>'ext.redactor.actions.ImageUpload',
                'uploadPath'=>Yii::app()->basePath . '/../images/user_img',
                'uploadUrl'=>'/images/user_img',
                'uploadCreate'=>true,
                'permissions'=>0755,
            ),
            'imageList'=>array(
                'class'=>'ext.redactor.actions.ImageList',
                'uploadPath'=>Yii::app()->basePath . '/../images/user_img',
                'uploadUrl'=>'/images/user_img',
            ),
        );
    }

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Comment']))
		{
			$model->attributes=$_POST['Comment'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
        if(Yii::app()->request->isPostRequest)
        {
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if(!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
        else
            throw new CHttpException(400,'Invalid request...');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
        $model=new Comment('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['Comment']))
            $model->attributes=$_GET['Comment'];

        $this->render('index',array(
            'model'=>$model,
        ));
	}

	/**
	 * Manages all models.
	 */
	/*public function actionAdmin()
	{
		$model=new Comment('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Comment']))
			$model->attributes=$_GET['Comment'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}*/

	public function actionApprove($id)
	{
	    if(Yii::app()->request->isPostRequest)
	    {
	        $comment=$this->loadModel($id);
	        $comment->approve();
            Yii::app()->end();
	    }
	    else
	        throw new CHttpException(400,'Invalid request...');
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Comment the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Comment::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Comment $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='comment-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/comment/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'comment-form',
    'enableAjaxValidation'=>true,
)); ?>

	<?php echo $form->errorSummary($model); ?>
	
	<label><?php echo $form->labelEx($model,'author'); ?></label>
	<?php echo $form->textField($model,'author',array('maxlength'=>128)); ?>
	<?php echo $form->error($model,'author'); ?>
	
	<label><?php echo $form->labelEx($model,'email'); ?></label>
	<?php echo $form->textField($model,'email',array('maxlength'=>128)); ?>
	<?php echo $form->error($model,'email'); ?>
	
	<label><?php echo $form->labelEx($model,'url'); ?></label>
	<?php echo $form->textField($model,'url',array('maxlength'=>128)); ?>
	<?php echo $form->error($model,'url'); ?>
	
	<label><?php echo $form->labelEx($model,'content'); ?></label>
	<?php //echo $form->textArea($model,'content'); ?>
    <?php $attribute='content';
    $this->widget('ext.redactor.ImperaviRedactorWidget',array(
        'model'=>$model,
        'attribute'=>$attribute,
        'options'=>array(
            'lang'=>'ru',
            'fileUploadErrorCallback'=>new CJavaScriptExpression(
                    'function(obj,json) { alert(json.error); }'
                ),
            'imageUpload'=>Yii::app()->createUrl('post/imageUpload',array(
                    'attr'=>$attribute
                )),
            'imageGetJson'=>Yii::app()->createUrl('post/imageList',array(
                    'attr'=>$attribute
                )),
            'imageUploadErrorCallback'=>new CJavaScriptExpression(
                    'function(obj,json) { alert(json.error); }'
                ),
        ),
    ));
    ?>
	<?php echo $form->error($model,'content'); ?>

    <!--label--><?php /*echo $form->labelEx($model,'status'); ?></label>
    <?php echo $form->dropDownList($model,'status',Lookup::items('CommentStatus')); ?>
    <?php echo $form->error($model,'status');*/ ?>
	
	<?php echo CHtml::submitButton($model->isNewRecord ? 'Отправить' : 'Сохранить', ['class'=>'button']); ?>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/comment/_form_user.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'comment-form',
    'enableAjaxValidation'=>true,
)); ?>

	<?php echo $form->errorSummary($model); ?>
	
	<label><?php echo $form->labelEx($model,'author'); ?></label>
	<?php echo $form->textField($model,'author',array('maxlength'=>128)); ?>
	<?php echo $form->error($model,'author'); ?>
	
	<label><?php echo $form->labelEx($model,'email'); ?></label>
	<?php echo $form->textField($model,'email',array('maxlength'=>128)); ?>
	<?php echo $form->error($model,'email'); ?>
	
	<label><?php echo $form->labelEx($model,'url'); ?></label>
	<?php echo $form->textField($model,'url',array('maxlength'=>128)); ?>
	<?php echo $form->error($model,'url'); ?>
	
	<label><?php echo $form->labelEx($model,'content'); ?></label>
	<?php //echo $form->textArea($model,'content'); ?>
    <?php $this->widget('ext.markitup.EMarkitupWidget', array(
        // можно использовать как для поля модели
        'model' => $model,
        'attribute' => 'content',
        'settings'=>'bbcode',

        // так и просто для элемента формы
        'name' => 'Comment[content]',
    ))?>
	<?php echo $form->error($model,'content'); ?>

    <!--label--><?php /*echo $form->labelEx($model,'status'); ?></label>
    <?php echo $form->dropDownList($model,'status',Lookup::items('CommentStatus')); ?>
    <?php echo $form->error($model,'status');*/ ?>
	
	<?php echo CHtml::submitButton($model->isNewRecord ? 'Отправить' : 'Сохранить', ['class'=>'button']); ?>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/comment/_search.php
<?php
/* @var $this CommentController */
/* @var $model Comment */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
        <?php echo $form->dropDownList($model,'status',[''=>'']+Lookup::items('CommentStatus')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'author'); ?>
		<?php echo $form->textField($model,'author',array('maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'url'); ?>
		<?php echo $form->textField($model,'url',array('maxlength'=>128)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Поиск', ['class'=>'button']); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/comment/_view.php
<?php
/* @var $this CommentController */
/* @var $data Comment */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('content')); ?>:</b>
	<?php echo CHtml::encode($data->content); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php echo CHtml::encode($data->status); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_time')); ?>:</b>
	<?php echo CHtml::encode($data->create_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('author')); ?>:</b>
	<?php echo CHtml::encode($data->author); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('url')); ?>:</b>
	<?php echo CHtml::encode($data->url); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('post_id')); ?>:</b>
	<?php echo CHtml::encode($data->post_id); ?>
	<br />

	*/ ?>

</div>

protected/views/comment/admin.php
<?php
/* @var $this CommentController */
/* @var $model Comment */

$this->breadcrumbs=array(
	'Управление комментариями',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#comment-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Управление комментариями</h1>

<?php echo CHtml::link('Расширенный поиск','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'comment-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'content',
		'status',
		'create_time',
		'author',
		'email',
		/*
		'url',
		'post_id',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/comment/create.php
<?php
/* @var $this CommentController */
/* @var $model Comment */

$this->breadcrumbs=array(
	'Comments'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Comment', 'url'=>array('index')),
	array('label'=>'Manage Comment', 'url'=>array('admin')),
);
?>

<h1>Create Comment</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/comment/index.php
<?php
/* @var $this CommentController */
/* @var $model Comment */

$this->breadcrumbs=array(
    'Управление комментариями',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#comment-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});");
?>

<h1>Управление комментариями</h1>

<?php echo CHtml::link('Расширенный поиск','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
    <?php $this->renderPartial('_search',array(
        'model'=>$model,
    )); ?>
</div><!-- search-form -->

<?php
//задаём количество строк на странице
$dataProvider = $model->search();
$dataProvider->setPagination(['pageSize'=>20]);

$this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'comment-grid',
    'dataProvider'=>$dataProvider,
    'filter'=>$model,
    //'summaryText'=>Yii::t('zii','Показаны {start}-{end} из 1 комментария.|Показаны {start}-{end} из {count} комментариев.',$model->search()->getTotalItemCount()),
    'pager'=>[
        'class'=>'CLinkPager',
        'header'=>'',
        'nextPageLabel'=>'&gt;',
        'prevPageLabel'=>'&lt;',
        'firstPageLabel'=>'&lt;&lt;',
        'lastPageLabel'=>'&gt;&gt;',
        'pageSize'=>20,
    ],
    'template'=>'{items}{pager}',
    'columns'=>array(
        [
            'name'=>'post.title',
            'type'=>'raw',
            'value'=>'CHtml::link(CHtml::encode($data->post->title), $data->post->url)',
            'header'=>Yii::t('comment', 'К посту'),
            'filter'=>false,
        ],
        array(
            'name'=>'content',
            'value'=>'Controller::shortContent($data->content, 150);',
            'filter'=>false,
            'htmlOptions'=>[
                'style'=>'width:320px;word-wrap: break-word;word-break: break-word;'
            ],
        ),
        array(
            'name'=>'status',
            'value'=>'Lookup::item("CommentStatus",$data->status)',
            'filter'=>Lookup::items('CommentStatus'),
            'htmlOptions'=>[
                'style'=>'width:90px;'
            ],
        ),
        array(
            'name'=>'create_time',
            'filter'=>false,
            'htmlOptions'=>[
                'style'=>'width:92px;'
            ],
        ),
        [
            'class'=>'CButtonColumn',
            'template' => '{approve}{update}{delete}',
            'buttons'=>
            [
                'approve' =>
                [
                    'label' => 'Одобрить',
                    'imageUrl' => '/i/approve.png',
                    'url' => 'Yii::app()->createUrl("comment/approve", array("id"=>$data->id))',
                    'options'=>['class'=>'approve'],
                    'visible'=>'$data->status==1',
                    'click'=><<<EOD
function() {
	if(!confirm('Одобрить комментарий?')) return false;
	jQuery('#comment-grid').yiiGridView('update', {
		type: 'POST',
		url: jQuery(this).attr('href'),
		success: function(data) {
			jQuery('#comment-grid').yiiGridView('update');
		},
	});
	return false;
}
EOD
                ],
            ],
            'htmlOptions'=>[
                'style'=>'width:76px;'
            ],
        ],
    ),
)); ?>

protected/views/comment/update.php
<?php
/* @var $this CommentController */
/* @var $model Comment */

$this->breadcrumbs=array(
	'Коммантарии'=>array('index'),
	'Изменение комментария',
);
?>

<h1>Изменение комментария</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/comment/view.php
<?php
/* @var $this CommentController */
/* @var $model Comment */

$this->breadcrumbs=array(
	'Comments'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Comment', 'url'=>array('index')),
	array('label'=>'Create Comment', 'url'=>array('create')),
	array('label'=>'Update Comment', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Comment', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Comment', 'url'=>array('admin')),
);
?>

<h1>View Comment #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'content',
		'status',
		'create_time',
		'author',
		'email',
		'url',
		'post_id',
	),
)); ?>